files 24.2.10 update

diff --git a/bin/dropbox-installer b/bin/dropbox-installer
--- a/bin/dropbox-installer
+++ b/bin/dropbox-installer
@@ -1,15 +1,21 @@
 #!/bin/bash
 echo ""
-read -p "   [0;33mDropbox Installer[0m
+read -p "   [0;32mDropbox Installer[0m
 
    This script will download and install Dropbox. Securely store, 
    organize, and share all of your files.
    
-   A web browser is recommended for dropbox initialization.
+   Note* A web browser is required for dropbox initialization.
+   firefox-esr will be installed if not already present.
    
-   [0;32mhttps://www.dropbox.com/[0m
+   [0;33mhttps://www.dropbox.com/[0m
    
-  [0;33m----------------------------------------
+   After installation, start dropbox from: 
+   [0;32mMenu --> All Programs --> Internet[0m
+   
+   Warning* - Do not use dropbox and Maestral at the same time!
+   
+  [0;32m----------------------------------------
    
    Please press enter to install Dropbox.
    
@@ -17,71 +23,56 @@ read -p "   [0;33mDropbox Installer[0m
       
    Or close this terminal window to quit the install." ;
 echo ""
-echo ""  
-full_fs=$(df ~ | tail -1 | awk '{print $1;}')  # find partition
-fs=$(basename "$full_fs")
 ### Check for internet connection
-   if : >/dev/tcp/8.8.8.8/53; then  
-### Find out if in Live environment and quit if so.
-if grep -q "$fs" /proc/partitions; then
-cd /tmp || exit
+   if : >/dev/tcp/8.8.8.8/53; then
+### Remove old configs
+rm -fr ~/.local/share/.dropbox-dist
+rm -fr ~/.dropbox
+### This will set thunar as the default manager
+xdg-mime default thunar.desktop inode/directory
 ### Install dependencies
 sudo apt update
-sudo apt-get install -y wget python3-gpg
-## Get rid of any left over packages in /tmp.
-rm -f /tmp/dropbox*
-wget https://raw.githubusercontent.com/sleekmason/packages/master/dropbox.zip --show-progress -q &&
-unzip -q /tmp/dropbox
+sudo apt-get install -y wget python3-gpg firefox-esr
 cd ~/.local/share || exit
 ### Grab dropbox.py for terminl use
 sudo wget -O /usr/local/bin/dropbox "https://www.dropbox.com/download?dl=packages/dropbox.py" &&
 sudo chmod +x /usr/local/bin/dropbox
-### Remove old configs
-rm -fr ~/.local/share/.dropbox-dist
-rm -fr ~/.dropbox
 ### Grab dropbox
 wget -O - "https://www.dropbox.com/download?plat=lnx.x86_64" | tar xzf - &&
-### Add .desktop file for autostart
-if [ ! -e "$HOME/.config/autostart" ]; then
-mkdir "$HOME/.config/autostart"
+echo ""
+echo "  [0;32m----------------------------------------------------------------------[0m"
+echo ""
+echo "   [0;32mStart dropbox from: Menu --> All Programs --> Internet[0m"
+echo ""
+echo "   [0;31mInitialization can take several seconds.[0m"
+echo "" 
+echo "   [0;32mLook in the system tray icon for options after initialization.[0m"
+echo ""  
+echo "   [0;31mTo have dropbox on login, see the Readme in ~/.config/autostart.[0m"
+echo ""  
+echo "   [0;32mType 'dropbox' in a terminal to see all the available commands.[0m"
+echo ""
+echo "  [0;32m----------------------------------------------------------------------[0m"
+echo ""
+### Initial start of dropbox if wanted
+# nohup ".dropbox-dist/dropboxd" > file 2>&1 &
+if ! test -e /usr/share/applications/dropbox.desktop; then
+sudo touch /usr/share/applications/dropbox.desktop
+{
+echo "[Desktop Entry]"
+echo "Type=Application"
+echo "Name=Dropbox"
+echo "Exec=sh -c ~/.local/share/.dropbox-dist/dropboxd"
+echo "StartupNotify=false"
+echo "Terminal=false"
+echo "Icon=web-browser"
+echo "Categories=Network;";} | sudo tee -a /usr/share/applications/dropbox.desktop > /dev/null
 fi
-if [ ! -e "$HOME/.config/autostart/dropbox.desktop" ]; then
-cp /tmp/dropbox.desktop ~/.config/autostart/dropbox.desktop
+if ! grep -q Firefox "$HOME/.config/jgmenu/prepend.csv"; then
+sed -i '/Firefox,            firefox,          firefox-esr/d' "$HOME/.config/jgmenu/prepend.csv"
+sed -i '7i Firefox,            firefox,          firefox-esr' "$HOME/.config/jgmenu/prepend.csv"
 fi
-### Initial start of dropbox
-nohup ".dropbox-dist/dropboxd" > file 2>&1 &
-### This will set thunar as the default manager
-xdg-mime default thunar.desktop inode/directory
-echo ""
-echo ""
-sleep 2
-echo "   [0;32mInstalling All ...[0m"
-echo ""
-sleep 1
-echo "   [0;32mStarting Dropbox ...[0m"
-sleep 1
-echo ""
-echo ""
-echo "  [0;32m----------------------------------------------------------------------"
-echo ""
-echo "   A .desktop file has been placed in ~/.config/autostart in order to"
-echo "   start dropbox on login.  Remove the autostart file or adjust as"
-echo "   desired if autostart is unwanted."
-echo ""
-echo "   The timeout is currently set for 20 seconds from login."
-echo ""
-echo "   Look in the system tray for a Dropbox icon, or look for"  
-echo "   terminal options by typing 'dropbox' in a terminal."
-echo ""
-echo "  ----------------------------------------------------------------------[0m"
-else
- echo "   [0;32m-------------------------------------------------------"
- echo ""
- echo "   Dropbox cannot be installed in a live environment."
- echo "   Install and try again!"
- echo ""
- echo "   -------------------------------------------------------[0m"
- fi
+# sleep 8
 else
 echo ""
  echo "   [0;31m-------------------------------------------------------"
